export const ECOSYSTEM_NAV_HEIGHT = 44;
export const DESKTOP_HEADER_HEIGHT = 72;
export const MOBILE_HEADER_HEIGHT = 64;
export const DESKTOP_STICKY_STACK_HEIGHT = ECOSYSTEM_NAV_HEIGHT + DESKTOP_HEADER_HEIGHT;
export const MOBILE_STICKY_STACK_HEIGHT = ECOSYSTEM_NAV_HEIGHT + MOBILE_HEADER_HEIGHT;
